server_port: 4000
baseurl:    /
url: https://beeradvent.com

markdown: kramdown
kramdown:
  input: GFM

permalink:   :day/:title

include:
  - _redirects
exclude:
  - node_modules
  - .sass-cache
  - tailwind.js
  - yarn.lock

sass:
  sass_dir: _scss
  style: :compressed
